name: example
description: An example for the Physik Engine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter
  physik:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
