name: physik
description: Physik, a verlet integration based physics engine for Flame.
version: 0.0.1
repository: https://github.com/wolfenrain/physik

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
