name: physik
description: Physik, a verlet integration based physics engine for Flame.
version: 0.0.1
repository: https://github.com/wolfenrain/physik

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.16.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
